project:
  type: website
  output-dir: docs

website:
  title: "quarto5"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - labs.qmd
      - project.qmd
      - presentation.qmd

format:
  html:
    theme: quartz
    css: styles.css
    toc: true

editor: visual

